import type { Certification, Experience, JourneyStat } from "@/types/journey";

export const FALLBACK_EXPERIENCES: Experience[] = [
  {
    id: "fallback-exp-1",
    title: "AI/ML Engineer & AI Solutions Architect",
    company: "",
    location: "Remote",
    period: "August 2024 – Present",
    employment_type: "Full-time",
    description:
      "Designing and developing production-ready AI/ML solutions focused on Generative AI, LLMs, AI agents, NLP, RAG and intelligent automation.",
    achievements: [
      "Developing LLM applications using Python, LangChain, LangGraph, OpenAI, Anthropic and Gemini.",
      "Building AI agents with tool calling, memory, workflow orchestration and multi-step reasoning.",
      "Working on RAG, embeddings, vector databases, semantic search and NLP-based classification.",
      "Implementing human-in-the-loop feedback and confidence-based AI workflows.",
      "Designing scalable AI backends using Python, FastAPI, Node.js and AWS.",
      "Leveraging 13+ years of software engineering experience to build complete production systems around AI.",
    ],
    technologies: [
      "Python",
      "LangChain",
      "LangGraph",
      "OpenAI",
      "Anthropic",
      "Gemini",
      "RAG",
      "Vector database",
      "Pinecone",
      "PGVector",
      "PostgreSQL",
      "AWS RDS",
      "FastAPI",
      "Node.js",
      "AWS",
    ],
    icon: "Brain",
    gradient: "from-[#EC4899] to-[#F97316]",
    published: true,
    sort_order: 1,
  },
  {
    id: "fallback-exp-2",
    title: "Sr. Tech Lead | AI, Cloud & Full-Stack Engineering",
    company: "",
    location: "Remote",
    period: "September 2020 – July 2024",
    employment_type: "Full-time",
    description:
      "Led architecture and development of scalable AI, cloud and full-stack applications.",
    achievements: [
      "Developed LLM-powered conversational applications using Python, LangChain, LangGraph and Gemini.",
      "Built AI-based industry classification systems using NLP, machine learning, LLMs, embeddings, NER and confidence scoring.",
      "Implemented multi-model classification combining rule-based and AI-driven predictions, with human-in-the-loop feedback workflows.",
      "Designed real-time AI systems using FastAPI and WebSockets.",
      "Worked with AWS Lambda, SQS, DynamoDB, Step Functions and CloudWatch.",
      "Led development using Node.js, React, Next.js, React Native and TypeScript.",
    ],
    technologies: [
      "Python",
      "LangChain",
      "LangGraph",
      "Gemini",
      "Vector database",
      "Pinecone",
      "PGVector",
      "PostgreSQL",
      "AWS RDS",
      "FastAPI",
      "WebSockets",
      "AWS Lambda",
      "SQS",
      "DynamoDB",
      "Step Functions",
      "Node.js",
      "React",
      "Next.js",
      "React Native",
      "TypeScript",
    ],
    icon: "Zap",
    gradient: "from-[#4A4E8C] to-[#6366F1]",
    published: true,
    sort_order: 2,
  },
  {
    id: "fallback-exp-3",
    title: "Tech Lead | IoT, Computer Vision & Cloud",
    company: "",
    location: "Remote",
    period: "August 2018 – August 2020",
    employment_type: "Full-time",
    description:
      "Led development of connected-device, cloud and intelligent application solutions involving real-time data, image processing and scalable backend systems.",
    achievements: [
      "Designed scalable cloud solutions supporting connected devices and high-volume communication.",
      "Developed REST APIs using Node.js, MongoDB, Redis and AWS.",
      "Worked with device-to-server communication and real-time data processing.",
      "Developed algorithms for route deviation, vehicle activity and operational metrics.",
      "Worked on computer vision and facial recognition capabilities using AWS AI services.",
      "Designed integrations and POCs for third-party systems.",
      "Led technical solution design and supervised developers.",
      "Developed applications using React.js, TypeScript and Redux.",
    ],
    technologies: [
      "Node.js",
      "MongoDB",
      "Redis",
      "AWS",
      "Computer Vision",
      "React.js",
      "TypeScript",
      "Redux",
    ],
    icon: "Database",
    gradient: "from-[#06B6D4] to-[#8B5CF6]",
    published: true,
    sort_order: 3,
  },
  {
    id: "fallback-exp-4",
    title: "Sr. Software Developer | IoT & Cloud Solutions",
    company: "",
    location: "Remote",
    period: "January 2015 – August 2018",
    employment_type: "Full-time",
    description:
      "Developed cloud-connected IoT and web/mobile applications focused on scalable backend systems, device communication and data-driven solutions.",
    achievements: [
      "Designed cloud architecture supporting multiple IoT device vendors and communication protocols.",
      "Developed REST APIs and backend services using Node.js, MongoDB and AWS.",
      "Integrated sensor and device-provider platforms into centralized cloud systems.",
      "Developed algorithms for vehicle tracking, route analysis and operational metrics.",
      "Built administration portals and monitoring applications.",
      "Worked with RabbitMQ, scheduled jobs and asynchronous processing.",
      "Developed web applications using AngularJS and React.js.",
      "Participated in architecture, system integration, POCs and production deployments.",
    ],
    technologies: [
      "Node.js",
      "MongoDB",
      "AWS",
      "RabbitMQ",
      "AngularJS",
      "React.js",
      "IoT",
    ],
    icon: "Code",
    gradient: "from-[#10B981] to-[#3B82F6]",
    published: true,
    sort_order: 4,
  },
];

export const FALLBACK_CERTIFICATIONS: Certification[] = [
  {
    id: "fallback-cert-1",
    title: "AWS Certified Cloud Practitioner",
    organization: "Amazon Web Services",
    year: "2023",
    expiry: "2026",
    description:
      "Foundational understanding of AWS Cloud concepts, services, and security",
    skills: ["Cloud Computing", "Amazon Web Services", "Cloud Services", "PaaS"],
    icon: "Award",
    color: "bg-[#FF9900]",
    verified: true,
    published: true,
    sort_order: 1,
  },
];

export const FALLBACK_STATS: JourneyStat[] = [
  { id: "fallback-stat-1", label: "Years Experience", value: "13+", icon: "Calendar", sort_order: 1 },
  { id: "fallback-stat-2", label: "Projects Completed", value: "16+", icon: "Code", sort_order: 2 },
  { id: "fallback-stat-3", label: "AI Models Deployed", value: "2+", icon: "Brain", sort_order: 3 },
  { id: "fallback-stat-4", label: "Happy Clients", value: "100%", icon: "Users", sort_order: 4 },
];
