import type { Project } from "@/types/project";

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: "fallback-1",
    slug: "ai-powered-document-assistant",
    title: "AI-Powered Document Assistant",
    summary:
      "Intelligent document processing using LangChain and OpenAI that extracts, analyzes, and answers questions from large document sets.",
    description:
      "Teams were drowning in PDFs, contracts, and internal wikis with no reliable way to ask questions across them. I designed a retrieval pipeline that chunks documents, stores embeddings, and answers in natural language with citations. The work covered ingestion, prompt design, evaluation against a golden set, and a Next.js UI for search and chat.",
    category: "AI/ML",
    icon: "Brain",
    gradient: "from-[#EC4899] to-[#F97316]",
    cover_image_url: null,
    live_url: "https://ai-document-assistant.vercel.app",
    github_url: "https://github.com/mohitagrawal/ai-document-assistant",
    role: "Full-stack + AI architecture",
    timeline: "12 weeks",
    outcome: "Cut document Q&A time from hours of manual search to seconds, with source citations on every answer.",
    tech_groups: [
      { label: "AI", items: ["LangChain", "OpenAI", "Vector DB"] },
      { label: "App", items: ["Next.js", "MongoDB"] },
    ],
    workflow: [
      { title: "Ingest", description: "Parse PDFs and docs, chunk by structure, and attach metadata for later citations." },
      { title: "Index", description: "Embed chunks and store them in a vector database with namespace isolation per tenant." },
      { title: "Retrieve", description: "Hybrid search plus reranking so answers stay grounded in the source files." },
      { title: "Answer", description: "Stream responses in the UI with quoted passages and confidence notes." },
    ],
    screenshots: [],
    featured: true,
    published: true,
    sort_order: 1,
  },
  {
    id: "fallback-2",
    slug: "conversational-ai-platform",
    title: "Conversational AI Platform",
    summary:
      "Multi-agent system built with LangGraph for complex conversational workflows across models and tools.",
    description:
      "A single chatbot could not handle routing, tools, and long-running tasks. I built a LangGraph orchestration layer where specialist agents hand off work, share state, and recover from tool failures. The platform sits behind a Node.js API with WebSockets so the UI can show agent steps live.",
    category: "AI/ML",
    icon: "Brain",
    gradient: "from-[#06B6D4] to-[#8B5CF6]",
    cover_image_url: null,
    live_url: "https://conversational-ai.vercel.app",
    github_url: "https://github.com/mohitagrawal/conversational-ai-platform",
    role: "Lead engineer, agent orchestration",
    timeline: "16 weeks",
    outcome: "Shipped multi-agent conversations with live tool traces and Redis-backed session memory.",
    tech_groups: [
      { label: "Agents", items: ["LangGraph", "LangChain"] },
      { label: "Runtime", items: ["Node.js", "WebSocket", "Redis"] },
    ],
    workflow: [
      { title: "Route", description: "Classify the user goal and pick a specialist graph, not a single mega-prompt." },
      { title: "Act", description: "Agents call tools with retries and structured output validation." },
      { title: "Remember", description: "Persist thread state in Redis so long sessions survive deploys." },
      { title: "Show", description: "Stream agent steps to the client so operators can debug a conversation." },
    ],
    screenshots: [],
    featured: true,
    published: true,
    sort_order: 2,
  },
  {
    id: "fallback-3",
    slug: "react-native-mobile-app-with-ai",
    title: "React Native Mobile App with AI",
    summary:
      "Cross-platform app with on-device and cloud AI: vision, language, and personalized content.",
    description:
      "The product needed camera-based recognition and personalized feeds without a slow native rewrite. I built the app in React Native and Expo, with TensorFlow Lite on device for latency-sensitive vision and a Python API for heavier NLP. Firebase handled auth, push, and remote config.",
    category: "Mobile",
    icon: "Smartphone",
    gradient: "from-[#6366F1] to-[#EC4899]",
    cover_image_url: null,
    live_url: "https://expo.dev/@mohitagrawal/ai-mobile-app",
    github_url: "https://github.com/mohitagrawal/react-native-ai-app",
    role: "Mobile + ML integration",
    timeline: "20 weeks",
    outcome: "Shipped iOS and Android from one codebase with on-device inference under 200ms for core vision tasks.",
    tech_groups: [
      { label: "Mobile", items: ["React Native", "Expo", "JavaScript"] },
      { label: "AI", items: ["Python", "TensorFlow Lite"] },
      { label: "Backend", items: ["Firebase"] },
    ],
    workflow: [
      { title: "Capture", description: "Camera pipeline with permission UX and compressed uploads when cloud is needed." },
      { title: "Infer", description: "Run TFLite on device; fall back to the Python API for heavier models." },
      { title: "Personalize", description: "Rank content from user events stored in Firebase." },
      { title: "Ship", description: "OTA updates via Expo and store builds for both platforms." },
    ],
    screenshots: [],
    featured: true,
    published: true,
    sort_order: 3,
  },
  {
    id: "fallback-4",
    slug: "fullstack-web-application",
    title: "Full-Stack Web Application",
    summary:
      "Enterprise web app with a React UI, Node/Express API, real-time updates, and a serious test suite.",
    description:
      "This was a greenfield product: auth, CRUD, live status, and an API other teams would consume. I set the React architecture, Express services, MongoDB schema, JWT auth, and WebSocket channels. Jest covered the API contracts that other squads depended on.",
    category: "Web App",
    icon: "Globe",
    gradient: "from-[#FCD34D] to-[#F97316]",
    cover_image_url: null,
    live_url: "https://fullstack-app.vercel.app",
    github_url: "https://github.com/mohitagrawal/fullstack-web-app",
    role: "Full-stack engineer",
    timeline: "24 weeks",
    outcome: "Delivered a production app with real-time updates and API tests as the contract for downstream teams.",
    tech_groups: [
      { label: "Frontend", items: ["React"] },
      { label: "Backend", items: ["Node.js", "Express", "JWT", "WebSocket"] },
      { label: "Data & quality", items: ["MongoDB", "Jest"] },
    ],
    workflow: [
      { title: "Model", description: "Define domain entities and JWT-protected routes around them." },
      { title: "Build", description: "React screens with optimistic UI for the high-traffic flows." },
      { title: "Sync", description: "WebSocket events for status so users do not refresh." },
      { title: "Prove", description: "Jest contract tests on the API before other teams integrated." },
    ],
    screenshots: [],
    featured: false,
    published: true,
    sort_order: 4,
  },
  {
    id: "fallback-5",
    slug: "ai-chatbot-integration",
    title: "AI Chatbot Integration",
    summary:
      "Product chatbot with NLU, conversation context, and multi-language replies inside an existing web app.",
    description:
      "Support needed a bot that understood intent, kept context, and did not break the host application. I combined Python NLU (NLTK, spaCy) with OpenAI for generation, a Node gateway, and Redis for session context. The widget attached to the existing site over WebSocket.",
    category: "AI/ML",
    icon: "Brain",
    gradient: "from-[#8B5CF6] to-[#EC4899]",
    cover_image_url: null,
    live_url: "https://ai-chatbot-demo.vercel.app",
    github_url: "https://github.com/mohitagrawal/ai-chatbot-integration",
    role: "NLP + integration",
    timeline: "10 weeks",
    outcome: "Embedded a context-aware bot in the existing product without a frontend rewrite.",
    tech_groups: [
      { label: "NLP", items: ["Python", "NLTK", "spaCy", "OpenAI API"] },
      { label: "Delivery", items: ["Node.js", "WebSocket", "Redis"] },
    ],
    workflow: [
      { title: "Understand", description: "Intent and entity extraction before any LLM call." },
      { title: "Ground", description: "Pull the last N turns and product facts from Redis." },
      { title: "Reply", description: "Generate in the user's language with fallback canned answers." },
      { title: "Embed", description: "Ship a small widget over WebSocket so the host app stays untouched." },
    ],
    screenshots: [],
    featured: false,
    published: true,
    sort_order: 5,
  },
  {
    id: "fallback-6",
    slug: "microservices-architecture",
    title: "Microservices Architecture",
    summary:
      "API gateway, service discovery, containers, and CI/CD with monitoring baked in from day one.",
    description:
      "A monolith was blocking independent deploys. I split core domains into Node services behind Nginx, containerized them, and ran them on Kubernetes. Jenkins pipelines, Prometheus, and Grafana made the new system operable instead of just 'distributed'.",
    category: "Architecture",
    icon: "Zap",
    gradient: "from-[#10B981] to-[#3B82F6]",
    cover_image_url: null,
    live_url: "https://microservices-demo.vercel.app",
    github_url: "https://github.com/mohitagrawal/microservices-architecture",
    role: "Platform / backend architecture",
    timeline: "18 weeks",
    outcome: "Teams could ship services independently with shared observability and a single ingress.",
    tech_groups: [
      { label: "Runtime", items: ["Node.js", "Docker", "Kubernetes", "Nginx"] },
      { label: "Ops", items: ["Prometheus", "Grafana", "Jenkins"] },
    ],
    workflow: [
      { title: "Split", description: "Carve bounded contexts and define API contracts per service." },
      { title: "Route", description: "API gateway and discovery so clients hit one stable edge." },
      { title: "Run", description: "Docker images on Kubernetes with resource limits and health checks." },
      { title: "Watch", description: "Metrics, logs, and CI/CD so failures are visible before users are." },
    ],
    screenshots: [],
    featured: false,
    published: true,
    sort_order: 6,
  },
  {
    id: "fallback-7",
    slug: "realtime-analytics-system",
    title: "Real-time Analytics System",
    summary:
      "Streaming analytics over large event volumes with live dashboards and ML-generated insights.",
    description:
      "Batch reports were too slow for operators. I designed a Kafka ingest path, Elasticsearch for query, Redis for hot aggregates, and a React + D3 dashboard. Python jobs scored anomalies and pushed insights next to the charts.",
    category: "Data Science",
    icon: "Database",
    gradient: "from-[#F59E0B] to-[#EF4444]",
    cover_image_url: null,
    live_url: "https://analytics-dashboard.vercel.app",
    github_url: "https://github.com/mohitagrawal/realtime-analytics-system",
    role: "Data platform + visualization",
    timeline: "14 weeks",
    outcome: "Operators saw live metrics and automated anomaly notes instead of overnight batch jobs.",
    tech_groups: [
      { label: "Stream", items: ["Python", "Apache Kafka", "Redis"] },
      { label: "Store", items: ["Elasticsearch", "PostgreSQL"] },
      { label: "UI", items: ["React", "D3.js"] },
    ],
    workflow: [
      { title: "Ingest", description: "Kafka topics per event type with back-pressure in mind." },
      { title: "Index", description: "Elasticsearch for search; Postgres for durable facts; Redis for hot counters." },
      { title: "Score", description: "Python jobs flag anomalies against rolling baselines." },
      { title: "Show", description: "D3 dashboards that update as the stream moves." },
    ],
    screenshots: [],
    featured: false,
    published: true,
    sort_order: 7,
  },
  {
    id: "fallback-8",
    slug: "ml-model-serving-platform",
    title: "ML Model Serving Platform",
    summary:
      "Production serving for ML models with autoscale, monitoring, and traffic splitting for experiments.",
    description:
      "Data science could train models but not run them safely. I built a FastAPI + TensorFlow Serving stack on Kubernetes, with Prometheus/Grafana and a simple way to split traffic for A/B tests. Docker images were the unit of deploy.",
    category: "ML Infrastructure",
    icon: "Zap",
    gradient: "from-[#8B5CF6] to-[#06B6D4]",
    cover_image_url: null,
    live_url: "https://ml-platform.vercel.app",
    github_url: "https://github.com/mohitagrawal/ml-serving-platform",
    role: "ML platform engineer",
    timeline: "15 weeks",
    outcome: "Models went from notebook to autoscale HTTP endpoints with live health and experiment traffic.",
    tech_groups: [
      { label: "Serving", items: ["Python", "FastAPI", "TensorFlow Serving"] },
      { label: "Platform", items: ["Docker", "Kubernetes", "Prometheus", "Grafana"] },
    ],
    workflow: [
      { title: "Package", description: "Versioned model images, not ad-hoc files on a VM." },
      { title: "Serve", description: "TF Serving + FastAPI gateway with request validation." },
      { title: "Scale", description: "K8s HPA on latency and CPU." },
      { title: "Experiment", description: "Traffic split between model versions with metrics per variant." },
    ],
    screenshots: [],
    featured: true,
    published: true,
    sort_order: 8,
  },
  {
    id: "fallback-9",
    slug: "vscode-extension-suite",
    title: "VS Code Extension Suite",
    summary:
      "VS Code extensions for AI development: completion helpers, debug views, and project templates.",
    description:
      "Internal AI work was slowed by copy-paste setup. I shipped a suite of VS Code extensions in TypeScript: snippets, a debug webview, and generators for common project shapes. Webpack bundled them; Jest and ESLint kept the API surface honest.",
    category: "Developer Tools",
    icon: "Code",
    gradient: "from-[#10B981] to-[#3B82F6]",
    cover_image_url: null,
    live_url: "https://marketplace.visualstudio.com/items?itemName=mohitagrawal.ai-suite",
    github_url: "https://github.com/mohitagrawal/vscode-ai-extensions",
    role: "Developer tools",
    timeline: "8 weeks",
    outcome: "Published a suite that turned repetitive AI project setup into a command palette flow.",
    tech_groups: [
      { label: "Extension", items: ["TypeScript", "VS Code API", "Webpack"] },
      { label: "Quality", items: ["Node.js", "Jest", "ESLint"] },
    ],
    workflow: [
      { title: "Map pain", description: "Watch how engineers started AI repos and list the repeated steps." },
      { title: "Extend", description: "Commands, views, and templates on the VS Code API." },
      { title: "Bundle", description: "Webpack + marketplace packaging." },
      { title: "Harden", description: "Jest for command logic, ESLint for the surface area." },
    ],
    screenshots: [],
    featured: false,
    published: true,
    sort_order: 9,
  },
  {
    id: "fallback-10",
    slug: "ai-model-training-pipeline",
    title: "AI Model Training Pipeline",
    summary:
      "Automated train, validate, and deploy loop with experiment tracking and versioned artifacts.",
    description:
      "Training was a pile of notebooks. I built a Kubeflow pipeline with MLflow tracking, Dockerized training jobs, Postgres metadata, Redis + Celery for async work, and a promotion path to serving only after validation gates passed.",
    category: "ML Infrastructure",
    icon: "Database",
    gradient: "from-[#F97316] to-[#EC4899]",
    cover_image_url: null,
    live_url: "https://ml-pipeline.vercel.app",
    github_url: "https://github.com/mohitagrawal/ai-training-pipeline",
    role: "MLOps",
    timeline: "12 weeks",
    outcome: "Replaced notebook training with a repeatable pipeline and a clear promote-to-prod gate.",
    tech_groups: [
      { label: "Pipeline", items: ["Python", "MLflow", "Kubeflow"] },
      { label: "Jobs", items: ["Docker", "Celery", "Redis"] },
      { label: "Metadata", items: ["PostgreSQL"] },
    ],
    workflow: [
      { title: "Track", description: "Every run logs params, metrics, and artifacts in MLflow." },
      { title: "Train", description: "Kubeflow steps on Dockerized jobs, queued through Celery when needed." },
      { title: "Gate", description: "Validation metrics must clear a threshold before promotion." },
      { title: "Promote", description: "Only passing versions are marked ready for the serving platform." },
    ],
    screenshots: [],
    featured: false,
    published: true,
    sort_order: 10,
  },
];
